private  object  Version {
    const val CORE_KTX = "1.2.0"
    const val  APP_COMPAT = "1.1.0"
    const val  MATERIAL = "1.1.0"
    const val  CONSTRAINT_LAYOUT = "1.1.3"
    const val NAVIGATION = "2.3.2"
    const val LIFECYCLE = "2.2.0"
    const val ANDROIDX_ANNOTATION = "1.1.0"
    const val DAGGER = "2.30.1"
    const val RETROFIT = "2.9.0"
    const val OKHTTP = "4.9.0"
    const val MOSHI = "1.11.0"
    const val STETHO = "1.5.1"
    const val LOGGING_INTERCEPTOR = "4.9.0"
}

object LibraryDependency {
    const val KOTLIN  = "org.jetbrains.kotlin:kotlin-stdlib:${CoreVersion.KOTLIN}"
    const val CORE_KTX = "androidx.core:core-ktx:${Version.CORE_KTX}"
    const val APP_COMPAT  = "androidx.appcompat:appcompat:${Version.APP_COMPAT}"
    const val MATERIAL =  "com.google.android.material:material:${Version.MATERIAL}"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout:${Version.CONSTRAINT_LAYOUT}"
    const val NAVIGATION_FRAGMENT_KTX = "androidx.navigation:navigation-fragment-ktx:${Version.NAVIGATION}"
    const val NAVIGATION_UI_KTX = "androidx.navigation:navigation-ui-ktx:${Version.NAVIGATION}"
    const val LIFECYCLE_LIVEDATA_KTX = "androidx.lifecycle:lifecycle-livedata-ktx:${Version.LIFECYCLE}"
    const val LIFECYCLE_VIEWMODEL_KTX= "androidx.lifecycle:lifecycle-viewmodel-ktx:${Version.LIFECYCLE}"
    const val ANDROIDX_ANNOTATION = "androidx.annotation:annotation:${Version.ANDROIDX_ANNOTATION}"
    const val DAGGER = "com.google.dagger:dagger:${Version.DAGGER}"
    const val DAGGER_COMPILER = "com.google.dagger:dagger-compiler:${Version.DAGGER}"
    const val RETROFIT = "com.squareup.retrofit2:retrofit:${Version.RETROFIT}"
    const val MOSHI_CONVERTER = "com.squareup.retrofit2:converter-moshi:${Version.RETROFIT}"
    const val OKHTTP = "com.squareup.okhttp3:okhttp:${Version.OKHTTP}"
    const val MOSHI = "com.squareup.moshi:moshi:${Version.MOSHI}"
    const val MOSHI_KOTLIN = "com.squareup.moshi:moshi-kotlin:${Version.MOSHI}"
    const val STETHO = "com.facebook.stetho:stetho:${Version.STETHO}"
    const val STETHO_OKHTTP = "com.facebook.stetho:stetho-okhttp3:${Version.STETHO}"
    const val LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor:${Version.LOGGING_INTERCEPTOR}"
}